package com.safezone.dto;

import java.util.List;

/**
 * Iso-intensity threat zone contour generated by the simulation model.
 * zoneType: THERMAL, BLAST, or COMBINED.
 * severityLevel: LOW, MODERATE, HIGH, CRITICAL.
 */
public record HazardZoneDto(
    String zoneId,
    String zoneType,
    double thresholdValue,
    String thresholdUnit,
    String severityLevel,
    Double radiusMeters,
    List<Point2D> polygonCoordinates,
    String description
) {}
